version: '3.9'

services:
  app:
    build: .
    image: flight-tracker:local
    container_name: flight-tracker
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app: